## Load configurations
- AmcCarrierCore:
    - AxiSy56040:
        - OutputConfig: !<value>
            - RTM_TIMING_IN0
            - BP_TIMING_IN
            - RTM_TIMING_IN1
            - FPGA_TIMING_IN
    - AmcCarrierTiming:
        - TimingFrameRx:
            - ClkSel: !<value> 0
